name: Beardsley
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161511'
    - '#fefccb'
    - '#b7aa75'
    - '#8c794f'
    - '#9d4714'
  brandStrength: 0.13770333863794804
  lightness: 0.25632089911960065
  saturation: 0.7214677568990737
  rhythmicContrast: 0.4208617815747857
purpose: []
